lb/urls.py
from django.conf.urls import url

from . import views

app_name='lb'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^environment/(?P<pk>[0-9]+)/$', views.environment_detail, name='environment_detail'),
    url(r'^environment/(?P<pk>[0-9]+)/Discussion/$',  views.environment_discussion, name='environment_discussion'),
    url(r'^environment/(?P<pk>[0-9]+)/Leaderboard/$',  views.environment_leaderboard, name='environment_leaderboard'),
    url(r'^environment/(?P<pk>[0-9]+)/Download/$',  views.environment_download, name='environment_download'),
    url(r'^environment/(?P<pk>[0-9]+)/download_zip/$',  views.download_file, name='download'),
    url(r'^submission/(?P<pk>[0-9]+)/Overview/$', views.submission_detail, name='submission_detail'),
    url(r'^submission/(?P<pk>[0-9]+)/BestRwards/$', views.submission_bestrwards, name='submission_bestrwards'),
    url(r'^submission/(?P<pk>[0-9]+)/Episodes/$', views.submission_episodes, name='submission_episodes'),
    url(r'^submission/(?P<pk>[0-9]+)/Discussion/$', views.submission_discussion, name='submission_discussion'),
    url(r'^accounts/profile/$', views.account_profile, name='account_profile'),
    url(r'^accounts/detail/(?P<username>[a-zA-Z0-9_\-\u4e00-\u9fa5]+)/$', views.account_detail, name='account_detail'),
    url(r'^environment/(?P<pk>[0-9]+)/Submit/$', views.submit, name='submit'),
    url(r'^environment_list/$', views.environment_list, name='environment_list'),
    url(r'^search/$', views.search, name='search'),
]

mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
# import notifications.urls
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('lb.urls')),
    url(r'^comments/', include('django_comments_xtd.urls')),
    # url(r'^notifications/', include(notifications.urls, namespace='notifications')),
    url(r'^accounts/',include('allauth.urls')),
    url(r'', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.MODEL_URL, document_root=settings.MODEL_ROOT)

urlpatterns +=[
    # url(r'^upload/(?P<path>.*)$','django.views.static.serve',{'document_root': settings.UPLOAD_ROOT }),
]

lb/forms.py
from django.forms import ModelForm
from .models import *
from django.db import models
#from ckeditor_uploader.fields import RichTextUploadingField
from django.forms import forms

class UserDetailForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'about','first_name','last_name','signature', 'title','department')

class SubmissionForm(ModelForm):
    checkpoints_file = forms.FileField()
    test_program_file = forms.FileField()
    class Meta:
        model = Submission
        fields = ('name','description','allow_comments')
        # fields = '__all__'

    def __init__(self,environment, user, *args, **kwargs):
        self.owner = user
        self.environment = environment
        super(SubmissionForm, self).__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.instance.owner = self.owner
        self.instance.environment = self.environment
        self.instance.score = self.score
        self.instance.sub_date = self.sub_date
        super(SubmissionForm, self).save(*args, **kwargs)

    def add_socre(self,score):
        self.score = score

    def add_time(self,sub_date):
        self.sub_date = sub_date

lb/views.py
import logging
import re
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger, InvalidPage
from .models import *
from django.http import StreamingHttpResponse
import os.path as osp
from .forms import *
from django.contrib.auth.decorators import login_required

import logging
logger = logging.getLogger('django')

def global_setting(request):
    return {'SITE_NAME':settings.SITE_NAME,'STIE_DESCP':settings.SITE_DESCP,'SITE_KEYWORDS':settings.SITE_KEYWORDS}

def get_page(request,environment_list,num=5):
    paginator = Paginator(environment_list,num)
    page = request.GET.get('page',1)
    try:
        environment_list = paginator.page(page)
    except(EmptyPage, PageNotAnInteger, InvalidPage):
        environment_list = paginator.page(1)
    return environment_list

def index(request):
    environment_list = Environment.objects.order_by("-click_count")
    environment_list = get_page(request,environment_list,num=6)
    return render(request, 'lb/index.html', context={'environment_list': environment_list})

def environment_list(request):
    environment_list = Environment.objects.order_by("-pub_date")
    environment_list = get_page(request,environment_list,num=9)
    return render(request, 'lb/environment_list.html', context={'environment_list': environment_list})

@login_required
def account_profile(request):
    messages = []
    if request.method == 'POST':
        request_dic = getattr(request, 'POST')
        form = UserDetailForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.append('successed change!')
    form = UserDetailForm(instance=request.user)
    return render(request, 'account/account_profile.html', context={'form':form,'messages':messages,})


def account_detail(request,username):
    subscriber = get_object_or_404(User,username=username)
    submission_list = Submission.objects.filter(owner=subscriber)
    environment_list = Environment.objects.filter(participants=subscriber)
    return render(request, 'account/account_detail.html', context={
        'subscriber': subscriber,
        'submission_list':submission_list,
        'environment_list':environment_list
    })


def environment_detail(request,pk):
    environment = get_object_or_404(Environment, pk=pk)
    environment.click_increase()
    category_list = environment.category.all()
    submission_list = Submission.objects.filter(environment=environment)
    participants_list = environment.participants.all()
    join_nb = 0
    for _ in participants_list:
        join_nb=join_nb+1
    return render(request, 'lb/environment_detail.html', context={
        'environment':environment,
        'join_nb':join_nb,
        'category_list': category_list,
        'submission_list': submission_list,
        'participants_list': participants_list
    })


def environment_leaderboard(request,pk):
    environment = get_object_or_404(Environment, pk=pk)
    category_list = environment.category.all()
    submission_list = Submission.objects.filter(environment=environment)
    participants_list = environment.participants.all()
    join_nb = 0
    for _ in participants_list:
        join_nb=join_nb+1
    return render(request,'lb/environment_leaderboard.html',context={
        'environment':environment,
        'submission_list': submission_list,
        'category_list': category_list,
        'join_nb': join_nb
    })


def environment_discussion(request,pk):
    environment = get_object_or_404(Environment, pk=pk)
    category_list = environment.category.all()
    participants_list = environment.participants.all()
    join_nb = 0
    for _ in participants_list:
        join_nb=join_nb+1
    return render(request,'lb/environment_discussion.html',context={
        'environment': environment,
        'category_list': category_list,
        'join_nb': join_nb
    })


def environment_download(request,pk):
    environment = get_object_or_404(Environment, pk=pk)
    category_list = environment.category.all()
    participants_list = environment.participants.all()
    join_nb = 0
    for _ in participants_list:
        join_nb=join_nb+1
    return render(request, 'lb/environment_download.html', context={
        'environment':environment,
        'category_list': category_list,
        'join_nb': join_nb
    })


def submission_detail(request,pk):
    submission = get_object_or_404(Submission, pk=pk)
    environment = submission.environment
    return render(request, 'lb/submission_detail.html', context={'submission':submission,
                                                        'environment':environment, })

def submission_bestrwards(request,pk):
    submission = get_object_or_404(Submission, pk=pk)
    environment = submission.environment
    owner = submission.owner
    return render(request,'lb/submission_bestrwards.html',context={'submission':submission, 
                                                       'owner':owner,
                                                        'environment':environment,})

def submission_episodes(request,pk):
    submission = get_object_or_404(Submission, pk=pk)
    environment = submission.environment
    owner = submission.owner
    return render(request,'lb/submission_episodes.html',context={'submission':submission,
                                                        'owner':owner,
                                                        'environment':environment,})

def submission_discussion(request,pk):
    submission = get_object_or_404(Submission, pk=pk)
    environment = submission.environment
    owner = submission.owner
    return render(request,'lb/submission_discussion.html',context={'submission':submission,
                                                        'owner':owner,
                                                        'environment':environment,})


def search(request):
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = 'Please submit a search term.'
        return render(request,'lb/search.html',context={'error_msg':error_msg})
    environment_list = Environment.objects.filter(name__contains = q)
    environment_list = get_page(request,environment_list)
    return render(request,'lb/search.html',context={'error_msg':error_msg,'environment_list':environment_list})


def upload(form, user, environment, sub_name, FILES):

    upload_path = "model/%s/%s/%s/" % (environment.name, user.username, sub_name)
    sub_time = datetime.datetime.now()
    sub_time_str = sub_time.strftime("%Y-%m-%d-%H-%M-%S-%f")
    upload_path = osp.join(upload_path, sub_time_str)
    upload_path +='/'
    # print('upload_path = '+upload_path)
    if os.path.isdir(upload_path):
        pass
    else:
        os.makedirs(upload_path)
    ckf = FILES.get("checkpoints_file", None)
    with open(osp.join(upload_path, "checkpoints"), "wb+") as destination:
        for chunk in ckf.chunks():
            destination.write(chunk)
    pgf = FILES.get("test_program_file", None)
    with open(osp.join(upload_path, "test_program.py"), "wb+") as destination:
        for chunk in pgf.chunks():
            destination.write(chunk)
    file_path = osp.dirname(os.path.abspath('manage.py'))
    run_path = osp.join(file_path, upload_path)
    run_path = osp.join(run_path, "test_program.py")
    run_commend = "python " + run_path + " --path " + upload_path
    print(run_commend)
    os.system(run_commend)

    score_path = osp.join(upload_path, 'score.txt')
    score_file = open(score_path, 'r')
    score = 0
    try:
        score = score_file.read()
        # print(score)
    finally:
        score_file.close()
    form.add_socre(score)

    if float(score) > environment.passing_line:
        environment.solved = 'solved'
    form.add_time(sub_time)

    form.save()


@login_required
def submit(request,pk):
    environment = get_object_or_404(Environment, pk=pk)
    messages = []
    if request.method == 'POST':

        form = SubmissionForm(environment,request.user,request.POST,request.FILES)
        form.owner = request.user
        form.environment = environment
        if form.is_valid():
            sub_name = request.POST.get('name','')

            if ' ' in sub_name:
                messages.append('Please input name without spaces')
                return render(request, 'lb/submit.html', context={'form':form,'error_messages': messages,'environment': environment})

            upload(form,request.user,environment,sub_name,request.FILES)

            messages.append('successed submit!')
            return render(request, 'lb/environment_leaderboard.html', context={
                'messages': messages,
                'environment': environment})
        else:
            messages.append('error1')
    else:
        form = SubmissionForm(environment,request)
    return render(request, 'lb/submit.html', context={
        'form':form,
        'messages':messages,
        'environment':environment})


def read_file(filename, chunk_size=512):
    with open(filename,'rb') as f:
        while True:
            c = f.read(chunk_size)
            if c:
                yield c
            else:
                break


def download_file(request,pk):
    environment = get_object_or_404(Environment, pk=pk)
    file_name = 'test_program.zip'
    filename = osp.join('model',environment.name)
    filename = osp.join(filename,file_name)
    reponse = StreamingHttpResponse(read_file(filename))
    reponse['Content-Type'] = 'application/octet-stream'
    reponse['Content-Disposition'] = 'attachment;filename="{0}"'.format(file_name)
    return reponse

templates/lb/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load lb_extras %}
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="description" content="">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Varela+Round" type='text/css'>
        <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <!-- Stylesheet -->
        <link rel="stylesheet" href="{% static 'css/style.css'%}">
	{% block extra_head %}
	{% endblock %}
  </head>
<body>
    <!-- Preloader -->
    <div id="preloader">
        <div class="spinner"></div>
    </div>

    <!-- ##### Header Start ##### -->
    <header class="header-area">

        <!-- Navbar Area -->
        <div class="clever-main-menu">
            <div class="classy-nav-container breakpoint-off">
                <!-- Menu -->
                <div class="container">
                <nav class="classy-navbar justify-content-between" id="cleverNav">

                    <!-- Logo -->
                    <a class="nav-brand" href="{% url 'lb:index' %}"><img src="/media/logo.jpg" alt="Logo" style="height: 80px"></a>

                    <!-- Navbar Toggler -->
                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>

                    <!-- Menu -->
                    <div class="classy-menu">

                        <!-- Close Button -->
                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>

                        <!-- Nav Start -->
                        <div class="classynav">
                            <ul>
                                <li><a href="{% url 'lb:index' %}">Home</a></li>
                                <li><a href="{% url 'lb:environment_list' %}">Environment</a></li>
                            </ul>

                            <!-- Search Button -->
                            <div class="search-area">
                                <form action="{% url 'lb:search' %}" method="get">
                                    <input type="search" name="q" id="search" placeholder="Search">
                                    <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                                </form>
                            </div>

                            <!-- Register / Login -->
                            <div class="register-login-area">
                                {% if user.is_authenticated %}
                                    <div class="login-state d-flex align-items-center">
                                        <div class="user-name mr-30">
                                            <div class="dropdown">
                                                <a class="dropdown-toggle" href="#" role="button" id="userName" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{user.username}}</a>
                                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userName">
                                                    <a class="dropdown-item" href="{% url 'lb:account_detail' user.username %}">Detail</a>
                                                    <a class="dropdown-item" href="{% url 'lb:account_profile' %}">Profile</a>
                                                    <a class="dropdown-item" href="{% url 'account_change_password' %}">Setting</a>
                                                    <a class="dropdown-item" href="{% url 'account_logout' %}">>LogOut</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="userthumb">
                                            {{ user.email|gravatar:50 }}
                                        </div>
                                    </div>
                                {% else %}
                                <a href="{% url 'account_signup' %}" class="btn">Register</a>
                                <a href="{% url 'account_login' %}" class="btn">Login</a>
                                {% endif %}
                            </div>

                        </div>
                        <!-- Nav End -->
                    </div>

                </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ##### Header End ##### -->

    <!-- ##### Message Start ##### -->
    <div class="content">
        {% if messages %}
            <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <ul>
                    {% for message in messages %}
                    <p>{{message}}</p>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    </div>
    <!-- ##### Message End ##### -->

    {% block content %}
    {% endblock %}

    <!-- ##### Footer Area Start ##### -->
    <footer class="footer-area">
        <!-- Top Footer Area -->
        <div class="top-footer-area">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="classynav">
                            <ul>
                                <li><a class="nav-link" style="color:white" href="#">FAQ</a></li>
                                <li><a class="nav-link" style="color:white" href="#">About us</a></li>
                                <li><a class="nav-link" style="color:white" href="#">Privacy</a></li>
                                <li><a class="nav-link" style="color:white" href="#">Terms of Service</a></li>
                                <li><a class="nav-link" style="color:white" href="#">Github</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->

</body>
    <!-- ##### All Javascript Script ##### -->
    <!--script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script-->
    <script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- jQuery-2.2.4 js -->
    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js/bootstrap/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <!-- All Plugins js -->
    <script src="{% static 'js/plugins/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>
</html>

templates/lb/environment_detail.html
{% extends 'lb/environment_head.html' %}
{% load staticfiles %}
{% load comments %}
{% load comments_xtd %}
{% block envthing %}
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'lb:environment_detail' environment.pk %}">Overview</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:environment_leaderboard' environment.pk %}">Leaderboard</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:environment_discussion' environment.pk %}">Discussion</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:environment_download' environment.pk %}">Download</a>
        </li>
    </ul>

    <div class="clever-description">

        <!-- About Course -->
        <div class="about-course mb-30">
            <h2>Overview</h2>
            <p>{{ environment.long_des|safe }}</p>
        </div>

    </div>

{% endblock envthing %}

templates/lb/environment_discussion.html
{% extends 'lb/environment_head.html' %}
{% load staticfiles %}
{% load comments %}
{% load comments_xtd %}
{% block envthing %}
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:environment_detail' environment.pk %}">Overview</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:environment_leaderboard' environment.pk %}">Leaderboard</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'lb:environment_discussion' environment.pk %}">Discussion</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:environment_download' environment.pk %}">Download</a>
        </li>
    </ul>

    <div class="clever-description">
        <div class="about-course mb-30">
            {% get_comment_count for environment as comment_count %}
            <h2>Discussion</h2>
            {% if comment_count %}
                {{ comment_count }} comments have been posted.
                <hr/>
                <div class="comments">
                    {% render_xtdcomment_tree for environment allow_feedback show_feedback%}
                </div>
            {% else %}
                <p>There has no posts</p>
            {% endif %}
            {% if environment.allow_comments %}
                <div class="comment">
                    <h2 class="text-center">Your comment</h2>
                    <div class="well">
                        {% render_comment_form for environment %}
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock envthing%}

templates/lb/environment_download.html
{% extends 'lb/environment_head.html' %}
{% load staticfiles %}
{% load comments %}
{% load comments_xtd %}
{% block envthing %}
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:environment_detail' environment.pk %}">Overview</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:environment_leaderboard' environment.pk %}">Leaderboard</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:environment_discussion' environment.pk %}">Discussion</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'lb:environment_download' environment.pk %}">Download</a>
        </li>
    </ul>

    <div class="clever-description">

        <!-- About Course -->
        <div class="about-course mb-30">
            <h2>Download</h2>
            <div>
                <h4>test_program.zip</h4>
                <a href="{% url 'lb:download' environment.pk %}">
                    <button class="btn clever-btn w-25">Download</button>
                </a>
            </div>
        </div>

    </div>
{% endblock envthing%}

templates/lb/environment_leaderboard.html
{% extends 'lb/environment_head.html' %}
{% load staticfiles %}
{% load comments %}
{% load comments_xtd %}
{% block envthing %}
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:environment_detail' environment.pk %}">Overview</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'lb:environment_leaderboard' environment.pk %}">Leaderboard</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:environment_discussion' environment.pk %}">Discussion</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:environment_download' environment.pk %}">Download</a>
        </li>
    </ul>

    <div class="clever-description">
        <div class="about-course mb-30">
            <h3>Leaderboard</h3>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Participant</th>
                        <th>Score</th>
                        <th>Submission date</th>
                    </tr>
                </thead>
                {% for submission in submission_list %}
                <tbody>
                    <td><a href="{% url 'lb:submission_detail' submission.pk %}">{{ submission.name }}</a></td>
                    <td><a href="{% url 'lb:account_detail'  submission.owner.username %}">{{ submission.owner }}</a></td>
                    <td>{{ submission.score}}</td>
                    <td>{{ submission.sub_date }}</td>
                </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock envthing%}

templates/lb/submission_bestrwards.html
{% extends 'lb/submission_head.html' %}
{% load staticfiles %}
{% load comments %}
{% load comments_xtd %}

{% block subthing %}
<div>
	<ul id="myTab" class="nav nav-tabs">
		<li><a href="{% url 'lb:submission' submission.pk%}">Overview</a></li>
		<li class="active"><a href="#">BestRwards</a></li>
		<li><a href="{% url 'lb:submission_episodes' submission.pk%}">Episodes</a></li>
		<li><a href="{% url 'lb:submission_discussion' submission.pk%}">Discussion</a></li>
	</ul>
	<div class="well well-lg">
			<h3>BestRwards</h3>
			<p>{{ submission.score }}</p>
	</div>
</div>
{% endblock subthing %}

templates/lb/submission_detail.html
{% extends 'lb/submission_head.html' %}
{% load staticfiles %}
{% load comments %}
{% load comments_xtd %}

{% block subthing %}
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'lb:submission_detail' submission.pk %}">Overview</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:submission_bestrwards' submission.pk %}">BestRwards</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:submission_episodes' submission.pk %}">Episodes</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:submission_discussion' submission.pk %}">Discussion</a>
        </li>
    </ul>
	<div class="well well-lg">
	    <div class="tab-content">
            <h3>Overview</h3>
            <p>{{ submission.description|safe }}</p>
	    </div>
    </div>
{% endblock subthing %}

templates/lb/submission_discussion.html
{% extends 'lb/submission_head.html' %}
{% load staticfiles %}
{% load comments %}
{% load comments_xtd %}

{% block subthing %}
<div>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:submission_detail' submission.pk %}">Overview</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:submission_bestrwards' submission.pk %}">BestRwards</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:submission_episodes' submission.pk %}">Episodes</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'lb:submission_discussion' submission.pk %}">Discussion</a>
        </li>
    </ul>
	<div class="well well-lg">
		{% get_comment_count for submission as comment_count %}
		<h3>Discussion</h3>
		{% if comment_count %}
		{{ comment_count }} comments have been posted.
			<hr/>
			<ul class="comments">
				{% render_xtdcomment_tree for submission allow_flagging allow_feedback show_feedback %}
			</ul>
		{% else %}
			<p>There has no posts</p>
		{% endif %}
		{% if submission.allow_comments %}
			<div class="comment">
				<h4 class="text-center">Your Comment</h4>
				<div class="well">
					{% render_comment_form for submission %}
				</div>
			</div>
		{% endif %}
	</div>
</div>
{% endblock subthing %}

templates/lb/submission_episodes.html
{% extends 'lb/submission_head.html' %}
{% load staticfiles %}
{% load comments %}
{% load comments_xtd %}

{% block subthing %}
<div>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:submission_detail' submission.pk %}">Overview</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:submission_bestrwards' submission.pk %}">BestRwards</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'lb:submission_episodes' submission %}">Episodes</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'lb:submission_discussion' submission.pk %}">Discussion</a>
        </li>
    </ul>
	<div class="well well-lg">
			<h3>Episodes</h3>
			<img src="{{ submission.get_gif_url }}" alt="Gif" style="width:1000px"/>
	</div>
</div>
{% endblock subthing %}